[package]
name = "compatibility_test"
version = "0.1.0"
authors = ["Timmy Jose <zoltan.jose@gmail.com>"]
edition = "2015"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
