[package]
name = "development_dependencies"
version = "0.1.0"
authors = ["Timmy Jose <zoltan.jose@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
pretty_assertions = "*"
